##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-utils
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - g++
    - git
    - gtk-doc-tools
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libmate-panel-applet-dev
    - libudisks2-dev
    - libx11-dev
    - libxext-dev
    - libxt-dev
    - make
    - mate-common
    - x11proto-xext-dev
    - xsltproc
    - yelp-tools
    - zlib1g-dev

before_scripts:
  - ./html-cppcheck
  # disable pt language for help in search tool
  - sed -i s/"IGNORE_HELP_LINGUAS ="/"IGNORE_HELP_LINGUAS = pt"/g gsearchtool/help/Makefile.am
  - ./install-from-git https://github.com/mate-desktop/mate-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
