#! /bin/sh

PACKAGE=cafe-utils;
DISK=cafe-disk-usage-analyzer;
SEARCH=cafe-search-tool;
LOG=cafe-system-log;
DICT=cafe-dictionary;

# main translations
make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
sed -i "/#, fuzzy/d" $PACKAGE.pot

# cafe-disk-usage-analyzer
make -C baobab/help $DISK.pot && mv baobab/help/$DISK.pot .

# cafe-search-tool
make -C gsearchtool/help $SEARCH.pot && mv gsearchtool/help/$SEARCH.pot .

# cafe-system-log
make -C logview/help $LOG.pot && mv logview/help/$LOG.pot .

# cafe-dictionary
make -C $DICT/help $DICT.pot && mv $DICT/help/$DICT.pot .
